[phases.setup]
nixPkgs = ['nodejs', 'npm']
aptPkgs = ['nodejs']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview'

[environment]
NODE_ENV = "production"